[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# EZ A JAVÍTOTT ÁTIRÁNYÍTÁS: A SPA (Single Page Application) frontend útvonalakhoz kell
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
