[build]
  publish = "."
  command = "echo 'No build needed'"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"

# SPA redirect (fontos!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions redirect
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
